version: 3.8 

services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD: password 
      - MYSQL_DATABASE: todo_db
    ports:
      - "3306:3306"

  web:
    ports:
      - "5000:5000"
    depends_on:
      - db 
    environment:
      - FLASK_ENV=development
      